### ISSUE TITLE
org.apache.jena.riot.lang.ReaderRIOTRDFXML NoClassDefFoundError Exception when deploying qa.hawk

### ISSUE THREAD

**Issue by santteegt** [dice-group/NLIWOD#56]
Hello,

I'm getting the a NoClassDefFoundError exception when trying to deploy hawk using docker. I tried adding the jena-arq dependency but then different classes appeared missing. What could be the problem ? I'm using the latest version of the source code

This is the entire stacktrace during spring startup:

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gerbilQABenchmarking' defined in file [/home/ciadmin/NLIWOD/qa.hawk/target/classes/org/aksw/hawk/webservice/GerbilQABenchmarking.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.aksw.hawk.webservice.GerbilQABenchmarking]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/jena/riot/lang/ReaderRIOTRDFXML
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1110)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1054)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at org.aksw.hawk.webservice.WebApplication.main(WebApplication.java:9)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.aksw.hawk.webservice.GerbilQABenchmarking]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/apache/jena/riot/lang/ReaderRIOTRDFXML
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1102)
	... 17 more
Caused by: java.lang.NoClassDefFoundError: org/apache/jena/riot/lang/ReaderRIOTRDFXML
	at org.apache.jena.tdb.TDB.init(TDB.java:248)
	at org.apache.jena.tdb.sys.InitTDB.start(InitTDB.java:29)
	at org.apache.jena.system.JenaSystem.lambda$init$1(JenaSystem.java:111)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:186)
	at org.apache.jena.system.JenaSystem.forEach(JenaSystem.java:163)
	at org.apache.jena.system.JenaSystem.init(JenaSystem.java:109)
	at org.apache.jena.rdf.model.ModelFactory.<clinit>(ModelFactory.java:49)
	at org.aksw.qa.annotation.index.IndexDBO_classes.index(IndexDBO_classes.java:115)
	at org.aksw.qa.annotation.index.IndexDBO_classes.<init>(IndexDBO_classes.java:63)
	at org.aksw.hawk.nlp.Annotater.<init>(Annotater.java:27)
	at org.aksw.hawk.controller.PipelineStanford.<init>(PipelineStanford.java:55)
	at org.aksw.hawk.webservice.GerbilQABenchmarking.<init>(GerbilQABenchmarking.java:28)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:142)
	... 19 more
Caused by: java.lang.ClassNotFoundException: org.apache.jena.riot.lang.ReaderRIOTRDFXML
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
```

**Comment by TortugaAttack** [comment]
should work now.

In Detail: 
The gerbil.nif.transfer qa.hawk is using is still using the jena versions 3.1.0 which do not have the `ReaderRIOTRDFXML` implemented.
Maven somehow always uses the older version in the dependency tree (thus 3.1.0 and not 3.6.0 even if you explicitly use the newer version) which lead to the Error. 

Fixed it by excluding the dependency from the nif.transfer dependency

**Comment by RicardoUsbeck** [comment]
Thanks, have a good night!
